import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link2, Plus, Trash2 } from 'lucide-react';
import Alert from '../../components/ui/Alert';
import Button from '../../components/ui/Button';
import Input from '../../components/ui/Input';
import Select from '../../components/ui/Select';
import LoadingSpinner from '../../components/LoadingSpinner';
import { useAuth } from '../../contexts/AuthContext';
import { useStaffProfile } from '../../contexts/StaffProfileContext';
import { useTenant } from '../../contexts/TenantContext';
import { recipesApi, mappingsApi } from './api';
import { recipeKeys } from './queries';
import { getErrorMessage } from '../../utils/errors';
export default function MappingsPage() {
  const { user } = useAuth(); const { activeTenant, isRootTenant } = useTenant(); const { loading, error, missing, hasPermission } = useStaffProfile(); const canRead = !isRootTenant && hasPermission('catalog.read'); const canManage = !isRootTenant && hasPermission('catalog.manage'); const p = user?.id ?? '', t = activeTenant?.tenantId ?? ''; const key = recipeKeys.mappings(p, t); const client = useQueryClient();
  const mappings = useQuery({ queryKey: key, queryFn: () => mappingsApi.list(), enabled: !!p && !!t && canRead }); const versions = useQuery({ queryKey: [...recipeKeys.all, 'released', p, t], queryFn: async () => { const recipes = (await recipesApi.list()).recipes; const all = await Promise.all(recipes.map(r => recipesApi.versions(r.id))); return all.flatMap((x, i) => x.recipeVersions.filter(v => v.status === 'released').map(v => ({ ...v, recipeName: recipes[i].name }))); }, enabled: !!p && !!t && canRead });
  const [form, setForm] = useState({ adapter: '', externalProductId: '', recipeVersionId: '', effectiveFrom: new Date().toISOString().slice(0, 10), effectiveTo: '' }); const [open, setOpen] = useState(false);
  const create = useMutation({ mutationFn: () => mappingsApi.create({ adapter: form.adapter, externalProductId: form.externalProductId, recipeVersionId: form.recipeVersionId, effectiveFrom: new Date(`${form.effectiveFrom}T00:00:00Z`).toISOString(), ...(form.effectiveTo ? { effectiveTo: new Date(`${form.effectiveTo}T00:00:00Z`).toISOString() } : {}) }), onSuccess: () => { void client.invalidateQueries({ queryKey: key }); setOpen(false); setForm({ ...form, adapter: '', externalProductId: '', recipeVersionId: '' }); } });
  const remove = useMutation({ mutationFn: (id: string) => mappingsApi.remove(id), onSuccess: () => void client.invalidateQueries({ queryKey: key }) });
  if (loading) return <LoadingSpinner size="lg" className="py-20" />;
  return <div className="space-y-7"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-primary-400"><Link2 className="h-4 w-4" />Integrations</div><h1 className="text-3xl font-bold tracking-tight text-white">POS mappings</h1><p className="mt-2 max-w-2xl text-dark-400">Point each external product at the recipe version that was valid when it sold.</p></div>{canManage && <Button onClick={() => setOpen(v => !v)} className="inline-flex items-center gap-2"><Plus className="h-4 w-4" />Add mapping</Button>}</header>
  {error ? <Alert>{getErrorMessage(error)}</Alert> : missing || !canRead ? <Alert>You do not have catalog access in this restaurant workspace.</Alert> : <>{!canManage && <Alert variant="info">You have read-only catalog access. A catalog manager can change mappings.</Alert>}{open && <form onSubmit={(e: FormEvent) => { e.preventDefault(); if (form.adapter && form.externalProductId && form.recipeVersionId) create.mutate(); }} className="grid gap-4 rounded-2xl border border-dark-800 bg-dark-900/70 p-5 sm:grid-cols-2 lg:grid-cols-5 lg:items-end"><Input label="POS adapter" required placeholder="square" value={form.adapter} onChange={e => setForm({ ...form, adapter: e.target.value.toLowerCase() })} /><Input label="External product ID" required placeholder="prod_123" value={form.externalProductId} onChange={e => setForm({ ...form, externalProductId: e.target.value })} /><Select label="Released recipe version" required value={form.recipeVersionId} onChange={e => setForm({ ...form, recipeVersionId: e.target.value })}><option value="">Choose version</option>{versions.data?.map(v => <option key={v.id} value={v.id}>{v.recipeName} · v{v.number}</option>)}</Select><Input label="Effective from" type="date" required value={form.effectiveFrom} onChange={e => setForm({ ...form, effectiveFrom: e.target.value })} /><div><Input label="Effective to (optional)" type="date" value={form.effectiveTo} onChange={e => setForm({ ...form, effectiveTo: e.target.value })} /><Button type="submit" className="mt-3 w-full" disabled={create.isPending}>{create.isPending ? 'Saving…' : 'Save mapping'}</Button></div>{create.isError && <Alert className="sm:col-span-2 lg:col-span-5">{getErrorMessage(create.error)}</Alert>}</form>}
  <section className="overflow-hidden rounded-2xl border border-dark-800 bg-dark-900/60"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-dark-800 text-xs uppercase tracking-wider text-dark-500"><tr><th className="px-5 py-4">Adapter</th><th className="px-5 py-4">External product</th><th className="px-5 py-4">Recipe version</th><th className="px-5 py-4">Effective range</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-dark-800">{mappings.isPending ? <tr><td colSpan={5}><LoadingSpinner className="py-12" /></td></tr> : (mappings.data?.mappings ?? []).map(m => { const v = versions.data?.find(x => x.id === m.recipeVersionId); return <tr key={m.id}><td className="px-5 py-4 font-medium text-primary-300">{m.adapter}</td><td className="px-5 py-4 font-mono text-xs text-white">{m.externalProductId}</td><td className="px-5 py-4 text-dark-300">{v ? `${v.recipeName} · v${v.number}` : <span className="text-dark-500">{m.recipeVersionId}</span>}</td><td className="px-5 py-4 text-dark-400">{new Date(m.effectiveFrom).toLocaleDateString()} → {m.effectiveTo ? new Date(m.effectiveTo).toLocaleDateString() : 'Open'}</td><td className="px-5 py-4 text-right">{canManage && <Button variant="danger" size="sm" aria-label={`Remove ${m.externalProductId}`} disabled={remove.isPending} onClick={() => remove.mutate(m.id)}><Trash2 className="h-4 w-4" /></Button>}</td></tr>})}</tbody></table></div>{!mappings.isPending && !(mappings.data?.mappings.length) && <div className="p-14 text-center"><Link2 className="mx-auto h-9 w-9 text-dark-600" /><h2 className="mt-3 font-medium text-white">No POS mappings yet</h2><p className="mt-1 text-sm text-dark-500">Add a mapping after releasing a recipe version.</p></div>}</section></>}</div>;
}
