import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, ArrowRightLeft, CheckCircle2, ClipboardList, Clock3, LockKeyhole, MapPin, Package, RefreshCw, ShieldAlert, ScanSearch } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import Alert from '../../components/ui/Alert';
import Button from '../../components/ui/Button';
import Input from '../../components/ui/Input';
import Select from '../../components/ui/Select';
import TableSkeleton from '../../components/TableSkeleton';
import { useAuth } from '../../contexts/AuthContext';
import { useActiveLocation } from '../../contexts/ActiveLocationContext';
import { useStaffProfile } from '../../contexts/StaffProfileContext';
import { useTenant } from '../../contexts/TenantContext';
import { getErrorMessage } from '../../utils/errors';
import { locationsApi } from '../locations/api';
import { inventoryApi } from './api';
import { inventoryKeys } from './queries';
import { validateInventoryForm, type InventoryFormErrors } from './validation';
import type { ActiveCountSummary, InventoryItemReference, InventoryStorageAreaReference, InventoryWriteInput, JournalEntry, StockBalance, StockLot, TransferInput, StockCountLine, ReconciliationRun } from './types';

const newKey = () => `inventory-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const prettyType: Record<string, string> = { opening_balance: 'Opening balance', manual_adjustment: 'Adjustment', reversal: 'Reversal', transfer: 'Transfer', waste: 'Waste', stock_count: 'Stock count' };
const qty = (value?: string) => value === undefined ? '—' : (Number(value) / 1_000_000).toLocaleString(undefined, { maximumFractionDigits: 6 });

export default function InventoryPage() {
  const { user } = useAuth(); const { activeTenant } = useTenant(); const { activeLocation, loading: locationLoading, error: locationError } = useActiveLocation();
  const { profile, loading: profileLoading, error: profileError, missing, hasPermission } = useStaffProfile(); const queryClient = useQueryClient();
  const navigate = useNavigate(); const route = useLocation(); const view = route.pathname.endsWith('/journal') ? 'journal' : route.pathname.endsWith('/lots') ? 'lots' : route.pathname.endsWith('/counts') ? 'counts' : route.pathname.endsWith('/reconciliation') ? 'reconciliation' : 'overview';
  const principal = user?.id ?? ''; const tenant = activeTenant?.tenantId ?? ''; const locationId = activeLocation?.id ?? ''; const canRead = hasPermission('inventory.read'); const canPost = hasPermission('inventory.post'); const canManage = hasPermission('inventory.manage'); const canOperate = canRead || canManage || canPost;
  const references = useQuery({ queryKey: inventoryKeys.references(principal, tenant, locationId), queryFn: () => inventoryApi.references(locationId), enabled: !!principal && !!tenant && !!locationId && canOperate });
  const locations = useQuery({ queryKey: ['locations', principal, tenant], queryFn: locationsApi.list, enabled: !!principal && !!tenant });
  const balances = useQuery({ queryKey: inventoryKeys.balances(principal, tenant, locationId), queryFn: () => inventoryApi.balances(locationId), enabled: (canRead || canPost) && !!locationId && !!principal && !!tenant });
  const [filter, setFilter] = useState(''); const journal = useQuery({ queryKey: inventoryKeys.journal(principal, tenant, locationId, filter), queryFn: () => inventoryApi.journal(locationId, filter || undefined), enabled: canRead && view === 'journal' && !!locationId && !!principal && !!tenant });
  const [selectedItem, setSelectedItem] = useState(''); const lots = useQuery({ queryKey: inventoryKeys.lots(principal, tenant, selectedItem), queryFn: () => inventoryApi.lots(selectedItem), enabled: (canRead || canPost) && view === 'lots' && !!selectedItem && !!tenant });
  const [entryType, setEntryType] = useState<'opening_balance' | 'adjustment' | 'waste' | 'transfer'>('adjustment'); const [form, setForm] = useState({ itemId: '', storageAreaId: '', quantity: '', reason: '', idempotencyKey: newKey(), lotId: '', destinationLocationId: '', destinationStorageAreaId: '' }); const [errors, setErrors] = useState<InventoryFormErrors>({}); const [message, setMessage] = useState('');
  const destinationReferences = useQuery({ queryKey: inventoryKeys.references(principal, tenant, form.destinationLocationId), queryFn: () => inventoryApi.references(form.destinationLocationId), enabled: canPost && entryType === 'transfer' && !!form.destinationLocationId });
  const entryLots = useQuery({ queryKey: inventoryKeys.lots(principal, tenant, form.itemId), queryFn: () => inventoryApi.lots(form.itemId), enabled: canPost && view === 'overview' && !!form.itemId && !!tenant });
  useEffect(() => { setForm(f => ({ ...f, storageAreaId: '', destinationStorageAreaId: '', lotId: '' })); }, [locationId]);
  useEffect(() => { setForm(f => f.lotId ? { ...f, lotId: '' } : f); }, [form.itemId]);
  const items = references.data?.items ?? []; const areas = references.data?.storageAreas ?? []; const names = useMemo(() => Object.fromEntries(items.map(i => [i.id, i.sku ? `${i.name} (${i.sku})` : i.name])), [items]); const areaNames = useMemo(() => Object.fromEntries(areas.map(a => [a.id, a.name])), [areas]);
  const selectedReference = items.find(item => item.id === form.itemId); const lotRequired = selectedReference?.lotTracking === 'required'; const needsAvailability = entryType === 'transfer' || entryType === 'waste';
  const selectableLots = useMemo(() => (entryLots.data?.lots ?? []).filter(lot => lot.status === 'available' && (!lot.expiresAt || new Date(lot.expiresAt) >= new Date()) && (!needsAvailability || (balances.data?.balances ?? []).some(balance => balance.itemId === form.itemId && balance.storageAreaId === form.storageAreaId && balance.lotId === lot.id && Number(balance.quantityMicros) > 0))), [entryLots.data?.lots, balances.data?.balances, form.itemId, form.storageAreaId, needsAvailability]);
  const createLot = useMutation({ mutationFn: ({ code, expiresAt }: { code: string; expiresAt?: string }) => inventoryApi.createLot(form.itemId, { code, ...(expiresAt ? { expiresAt } : {}), status: 'available' }), onSuccess: result => { set('lotId', result.lot.id); setMessage('Lot created and selected.'); queryClient.invalidateQueries({ queryKey: inventoryKeys.lots(principal, tenant, form.itemId) }); }, onError: error => setMessage(getErrorMessage(error)) });
  const mutation = useMutation({ mutationFn: (input: InventoryWriteInput | TransferInput) => entryType === 'opening_balance' ? inventoryApi.openingBalance(locationId, input) : entryType === 'waste' ? inventoryApi.waste(locationId, input) : entryType === 'transfer' ? inventoryApi.transfer(locationId, input as TransferInput) : inventoryApi.adjustment(locationId, input), onSuccess: () => { setMessage('Inventory entry posted.'); setForm(f => ({ ...f, quantity: '', reason: '', idempotencyKey: newKey() })); queryClient.invalidateQueries({ queryKey: inventoryKeys.all }); }, onError: e => setMessage(getErrorMessage(e)) });
  const submit = (event: FormEvent) => { event.preventDefault(); const next = validateInventoryForm(form, entryType === 'transfer', lotRequired); if (form.lotId && !selectableLots.some(lot => lot.id === form.lotId)) next.lotId = needsAvailability ? 'This lot is not available in the source area.' : 'This lot is unavailable or invalid.'; setErrors(next); if (Object.keys(next).length || !canPost || !locationId) return; mutation.mutate({ storageAreaId: form.storageAreaId, itemId: form.itemId, quantity: form.quantity, reason: form.reason.trim(), idempotencyKey: form.idempotencyKey.trim(), ...(form.lotId ? { lotId: form.lotId } : {}), ...(entryType === 'transfer' ? { destinationLocationId: form.destinationLocationId, destinationStorageAreaId: form.destinationStorageAreaId } : {}) }); };
  const set = (key: keyof typeof form, value: string) => { setForm(f => ({ ...f, [key]: value })); setErrors(e => ({ ...e, [key]: undefined })); setMessage(''); };

  if (profileLoading || locationLoading) return <div className="space-y-6"><div className="h-20 animate-pulse rounded-2xl bg-dark-900" /><TableSkeleton rows={5} cols={4} /></div>;
  if (profileError || locationError) return <State icon={AlertCircle} title="Inventory could not load" copy={getErrorMessage(profileError || locationError)} />;
  if (missing || !profile || !canOperate) return <State icon={LockKeyhole} title="Inventory access unavailable" copy="Your staff profile does not grant inventory access at this location. Ask a workspace owner to update your access." />;
  if (!activeLocation) return <State icon={MapPin} title="Select an active location" copy="Inventory balances and journal entries are kept per location. Choose a location from the header to continue." />;
  if (references.isError) return <State icon={isForbidden(references.error) ? LockKeyhole : AlertCircle} title={isForbidden(references.error) ? 'Inventory references forbidden' : 'Inventory references could not load'} copy={getErrorMessage(references.error)} action={references.refetch} />;
  const balanceRows = balances.data?.balances ?? [];
  return <div className="space-y-7">
    <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-primary-400"><Package className="h-4 w-4" />Operations</div><h1 className="text-3xl font-bold tracking-tight text-white">Inventory</h1><p className="mt-2 max-w-2xl text-dark-400">Know what is on hand, where it lives, and what moved at <span className="text-dark-200">{activeLocation.name}</span>.</p></div><div className="flex items-center gap-3 rounded-xl border border-primary-500/20 bg-primary-500/10 px-4 py-3"><MapPin className="h-5 w-5 text-primary-400" /><div><p className="text-[11px] uppercase tracking-wider text-primary-400">Active location</p><p className="font-semibold text-white">{activeLocation.name}</p></div></div></header>
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-dark-800 bg-dark-900/60 p-1"><Tab active={view === 'overview'} onClick={() => navigate('/inventory')} icon={Package}>Balances</Tab><Tab active={view === 'journal'} onClick={() => navigate('/inventory/journal')} icon={ClipboardList}>Journal</Tab><Tab active={view === 'lots'} onClick={() => navigate('/inventory/lots')} icon={Clock3}>Lots & expiry</Tab><Tab active={view === 'counts'} onClick={() => navigate('/inventory/counts')} icon={CheckCircle2}>Counts</Tab><Tab active={view === 'reconciliation'} onClick={() => navigate('/inventory/reconciliation')} icon={ScanSearch}>Reconciliation</Tab></nav>
    {view === 'counts' && <CountWorkflowV2 locationId={locationId} principal={principal} tenant={tenant} areas={areas} items={items} canRead={canRead} canManage={canManage} canPost={canPost} />}
    {view === 'reconciliation' && <ReconciliationPanel locationId={locationId} principal={principal} tenant={tenant} areas={areas} items={items} canRead={canRead} canManage={canManage} />}
    {!canPost && <Alert variant="info" className="flex items-center gap-2"><LockKeyhole className="h-4 w-4" /><span><strong>Read-only access.</strong> You can inspect inventory, but posting changes requires inventory post permission.</span></Alert>}
    {view === 'overview' && <><section className="overflow-hidden rounded-2xl border border-dark-800 bg-dark-900/50"><div className="flex items-center justify-between border-b border-dark-800 px-5 py-4"><div><h2 className="font-semibold text-white">On hand now</h2><p className="text-xs text-dark-500">Balances are scoped to this location.</p></div><span className="rounded-full bg-accent-emerald/10 px-2.5 py-1 text-xs text-accent-emerald">{balanceRows.length} lines</span></div>{balances.isPending ? <TableSkeleton rows={4} cols={4} /> : balances.isError ? <InlineState title="Could not load balances" error={balances.error} retry={balances.refetch} /> : balanceRows.length === 0 ? <State icon={Package} title="No stock recorded yet" copy="Post an opening balance or adjustment to start building this location's inventory." compact /> : <BalanceTable rows={balanceRows} names={names} areaNames={areaNames} />}</section><EntryPanel {...{ canPost, canManage, items, areas, locations: locations.data?.locations ?? [], destinationAreas: destinationReferences.data?.storageAreas ?? [], entryType, setEntryType, form, errors, set, submit, pending: mutation.isPending, message, lots: entryLots.data?.lots ?? [], lotsLoading: entryLots.isPending, lotsError: entryLots.error, selectableLots, lotRequired, needsAvailability, createLot: (code: string, expiresAt?: string) => createLot.mutate({ code, expiresAt }), creatingLot: createLot.isPending }} /></>}
    {view === 'journal' && <section className="overflow-hidden rounded-2xl border border-dark-800 bg-dark-900/50"><div className="flex flex-col gap-3 border-b border-dark-800 px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-semibold text-white">Stock journal</h2><p className="text-xs text-dark-500">Immutable entries recorded at this location.</p></div><Select label="Filter by item" value={filter} onChange={e => setFilter(e.target.value)} className="sm:w-64"><option value="">All items</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</Select></div>{journal.isPending ? <TableSkeleton rows={5} cols={4} /> : journal.isError ? <InlineState title="Could not load journal" error={journal.error} retry={journal.refetch} /> : (journal.data?.journal ?? []).length === 0 ? <State icon={ClipboardList} title="No journal entries" copy={filter ? 'No entries match this item.' : 'Changes to stock will appear here once they are posted.'} compact /> : <JournalTable entries={journal.data?.journal ?? []} names={names} areaNames={areaNames} />}</section>}
    {view === 'lots' && <section className="rounded-2xl border border-dark-800 bg-dark-900/50"><div className="border-b border-dark-800 px-5 py-4"><h2 className="font-semibold text-white">Lots, expiry & quarantine</h2><p className="text-xs text-dark-500">Choose an item to inspect its traceable stock.</p></div><div className="p-5"><Select label="Item" value={selectedItem} onChange={e => setSelectedItem(e.target.value)}><option value="">Select an item</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</Select>{selectedItem && (lots.isPending ? <TableSkeleton rows={3} cols={3} /> : lots.isError ? <InlineState title="Could not load lots" error={lots.error} retry={lots.refetch} /> : <LotTable itemId={selectedItem} lots={lots.data?.lots ?? []} canManage={canManage} />)}</div></section>}
  </div>;
}

function isForbidden(error: unknown) { return typeof error === 'object' && error !== null && 'response' in error && (error as { response?: { status?: number } }).response?.status === 403; }
function isConflict(error: unknown) { return typeof error === 'object' && error !== null && 'response' in error && (error as { response?: { status?: number } }).response?.status === 409; }
const microsToDecimal = (value?: string) => value === undefined ? '' : (Number(value) / 1_000_000).toFixed(6).replace(/\.?(0+)$/, '');
const signedQty = (value: string) => `${Number(value) < 0 ? '' : '+'}${qty(value)}`;

function ActiveCountPicker({ counts, nextCursor, pending, error, retry, loadMore, canManage, areaId, areas, setAreaId, onSelect, onStart, starting, message, onCancelled }: { counts: ActiveCountSummary[]; nextCursor?: string; pending: boolean; error: unknown; retry: () => void; loadMore: () => void; canManage: boolean; areaId: string; areas: InventoryStorageAreaReference[]; setAreaId: (value: string) => void; onSelect: (id: string) => void; onStart: () => void; starting: boolean; message: string; onCancelled: () => void }) {
  const healthy = counts.filter(summary => summary.integrity === 'healthy');
  return <section className="space-y-5"><div className="rounded-2xl border border-dark-800 bg-dark-900/70 p-5 sm:p-6"><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 h-5 w-5 text-primary-400" /><div><h2 className="text-lg font-semibold text-white">Active physical counts</h2><p className="mt-1 max-w-2xl text-sm text-dark-400">Resume a healthy count, or start a new one when the area is ready.</p></div></div>{pending ? <TableSkeleton rows={3} cols={3} /> : error ? <InlineState title="Could not load active counts" error={error} retry={retry} /> : <div className="mt-5 space-y-3">{healthy.map(summary => <ActiveCountCard key={summary.count.id} summary={summary} onSelect={() => onSelect(summary.count.id)} />)}{counts.filter(summary => summary.integrity !== 'healthy').map(summary => <QuarantinedCountCard key={summary.count.id} summary={summary} canManage={canManage} onCancelled={onCancelled} />)}{counts.length === 0 && <p className="rounded-xl border border-dark-800 bg-dark-950/30 p-4 text-sm text-dark-400">No active counts need your attention.</p>}{nextCursor && <Button variant="secondary" disabled={pending} onClick={loadMore} className="w-full">{pending ? 'Loading…' : 'Load more active counts'}</Button>}</div>}</div><div className="rounded-2xl border border-dark-800 bg-dark-900/70 p-5 sm:p-6"><h3 className="font-semibold text-white">Start a physical count</h3><p className="mt-1 text-sm text-dark-400">Freezing records the snapshot and pauses normal inventory activity there until this count is posted or cancelled.</p><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end"><Select label="Storage area" value={areaId} onChange={e => setAreaId(e.target.value)} className="min-w-0 flex-1"><option value="">Choose an area</option>{areas.map(area => <option key={area.id} value={area.id}>{area.name}</option>)}</Select><Button disabled={!areaId || starting || !canManage} onClick={onStart}>{starting ? 'Starting…' : 'Start draft count'}</Button></div>{!canManage && <p className="mt-3 text-xs text-dark-500">Inventory manage permission is required to start a count.</p>}{message && <p className="mt-4 text-sm text-dark-300">{message}</p>}</div></section>;
}

function ActiveCountCard({ summary, onSelect }: { summary: ActiveCountSummary; onSelect: () => void }) { return <button onClick={onSelect} className="flex w-full items-center justify-between rounded-xl border border-primary-500/20 bg-primary-500/5 p-4 text-left transition hover:border-primary-500/50"><div><p className="font-medium text-white">Count in {summary.count.status} state</p><p className="mt-1 text-sm text-dark-400">Area {summary.count.storageAreaId} · updated {new Date(summary.count.updatedAt).toLocaleString()}</p></div><span className="text-sm font-medium text-primary-300">Resume →</span></button>; }

function QuarantinedCountCard({ summary, canManage, onCancelled }: { summary: ActiveCountSummary; canManage: boolean; onCancelled: () => void }) { const cancel = useMutation({ mutationFn: () => inventoryApi.cancelCount(summary.count.locationId, summary.count.id, summary.count.version), onSuccess: onCancelled }); return <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-amber-200">Count needs attention</p><p className="mt-1 text-sm text-dark-400">This count is quarantined ({summary.integrity.replace('_', ' ')}). Line details are unavailable until it is resolved.</p></div>{canManage && <Button variant="secondary" size="sm" disabled={cancel.isPending} onClick={() => cancel.mutate()}>{cancel.isPending ? 'Cancelling…' : 'Cancel count safely'}</Button>}</div><p className="mt-3 text-xs text-dark-500">Cancelling releases only locks owned by this count; it does not change other inventory locks.</p></div>; }

function CountWorkflowV2({ locationId, principal, tenant, areas, items, canRead, canManage, canPost }: { locationId: string; principal: string; tenant: string; areas: InventoryStorageAreaReference[]; items: InventoryItemReference[]; canRead: boolean; canManage: boolean; canPost: boolean }) {
  const queryClient = useQueryClient(); const navigate = useNavigate(); const route = useLocation(); const [areaId, setAreaId] = useState(''); const [countId, setCountId] = useState(() => new URLSearchParams(route.search).get('countId') ?? ''); const [message, setMessage] = useState(''); const [lineInputs, setLineInputs] = useState<Record<string, string>>({}); const [discoverItemId, setDiscoverItemId] = useState(''); const [discoverLotId, setDiscoverLotId] = useState(''); const [activeCursor, setActiveCursor] = useState(''); const [activeNextCursor, setActiveNextCursor] = useState<string>(); const [activePages, setActivePages] = useState<Array<{ cursor: string; nextCursor?: string; counts: ActiveCountSummary[] }>>([]); const [activeResetPending, setActiveResetPending] = useState(false);
  const activeCounts = useQuery({ queryKey: inventoryKeys.activeCounts(principal, tenant, locationId, activeCursor), queryFn: () => inventoryApi.listActiveCounts(locationId, activeCursor ? { cursor: activeCursor } : undefined), enabled: (canRead || canManage || canPost) && !!locationId && !!principal && !!tenant && !countId });
  useEffect(() => { if (!activeCounts.data || activeResetPending) return; setActivePages(pages => { const index = pages.findIndex(page => page.cursor === activeCursor); if (index !== -1) return pages.map((page, i) => i === index ? { cursor: activeCursor, nextCursor: activeCounts.data!.nextCursor, counts: activeCounts.data!.counts } : page); if (activeCursor && !pages.some(page => page.nextCursor === activeCursor)) return pages; return [...pages, { cursor: activeCursor, nextCursor: activeCounts.data!.nextCursor, counts: activeCounts.data!.counts }]; }); setActiveNextCursor(activeCounts.data.nextCursor); }, [activeCounts.data, activeCursor, activeResetPending]);
  useEffect(() => { setActiveCursor(''); setActiveNextCursor(undefined); setActivePages([]); setActiveResetPending(false); }, [principal, tenant, locationId]);
  useEffect(() => { if (!activeResetPending || countId || activeCursor !== '') return; void activeCounts.refetch().then(() => setActiveResetPending(false)); }, [activeCounts.refetch, activeCursor, activeResetPending, countId]);
  const activeRows = useMemo(() => activePages.flatMap(page => page.counts), [activePages]);
  useEffect(() => { const next = new URLSearchParams(route.search).get('countId') ?? ''; if (next !== countId) setCountId(next); }, [route.search, countId]);
  const selectCount = (id: string) => { setCountId(id); navigate(`/inventory/counts?countId=${encodeURIComponent(id)}`); };
  const count = useQuery({ queryKey: inventoryKeys.count(principal, tenant, locationId, countId), queryFn: () => inventoryApi.getCount(locationId, countId), enabled: (canRead || canManage || canPost) && !!locationId && !!countId });
  const discoveredLots = useQuery({ queryKey: inventoryKeys.countLotOptions(principal, tenant, locationId, countId, discoverItemId), queryFn: () => inventoryApi.listCountLotOptions(locationId, countId, discoverItemId), enabled: canManage && !!countId && !!discoverItemId });
  const create = useMutation({ mutationFn: () => inventoryApi.createCount(locationId, areaId, newKey()), onSuccess: result => { setCountId(result.count.id); setAreaId(result.count.storageAreaId); setMessage('Draft count started. Freeze it when the team is ready to count.'); }, onError: error => setMessage(getErrorMessage(error)) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: inventoryKeys.count(principal, tenant, locationId, countId) });
  const freeze = useMutation({ mutationFn: () => inventoryApi.freezeCount(locationId, countId, count.data!.count.version), onSuccess: refresh, onError: error => setMessage(isConflict(error) ? 'This count changed in another session. Refresh before continuing.' : getErrorMessage(error)) });
  const record = useMutation({ mutationFn: ({ line, value }: { line: StockCountLine; value: string }) => inventoryApi.recordCountLine(locationId, countId, line.id, { countVersion: count.data!.count.version, lineVersion: line.version, countedQuantity: value }), onSuccess: refresh, onError: error => { setMessage(isConflict(error) ? 'This count changed while you recorded it. Refresh before continuing.' : getErrorMessage(error)); refresh(); } });
  const discover = useMutation({ mutationFn: () => inventoryApi.discoverCountLine(locationId, countId, { countVersion: count.data!.count.version, itemId: discoverItemId, ...(discoverLotId ? { lotId: discoverLotId } : {}) }), onSuccess: () => { setDiscoverItemId(''); setDiscoverLotId(''); setMessage('Discovered item added with an expected quantity of zero.'); refresh(); }, onError: error => setMessage(isConflict(error) ? 'This count changed while you added the item. Refresh before continuing.' : getErrorMessage(error)) });
  const review = useMutation({ mutationFn: () => inventoryApi.reviewCount(locationId, countId, count.data!.count.version), onSuccess: refresh, onError: error => setMessage(isConflict(error) ? 'The count changed while you reviewed it. Refresh and try again.' : getErrorMessage(error)) });
  const cancel = useMutation({ mutationFn: () => inventoryApi.cancelCount(locationId, countId, count.data!.count.version), onSuccess: result => { queryClient.setQueryData(inventoryKeys.count(principal, tenant, locationId, countId), result); setMessage('Count cancelled. Only locks owned by this count may now be released; other inventory locks are unaffected.'); }, onError: error => setMessage(isConflict(error) ? 'This count changed in another session. Refresh before cancelling.' : getErrorMessage(error)) });
  const post = useMutation({ mutationFn: () => inventoryApi.postCount(locationId, countId, newKey()), onSuccess: result => { setMessage('Count posted. Normal inventory activity is available again.'); queryClient.setQueryData(inventoryKeys.count(principal, tenant, locationId, countId), result); }, onError: error => setMessage(getErrorMessage(error)) });
  if (!canRead && !canManage && !canPost) return <State icon={LockKeyhole} title="Count access unavailable" copy="You need inventory access to inspect counts at this location." />;
  const resetActiveList = () => { setActiveCursor(''); setActiveNextCursor(undefined); setActivePages([]); setActiveResetPending(true); };
  if (!countId) return ActiveCountPicker({ counts: activeRows, nextCursor: activeNextCursor, pending: activeCounts.isPending || activeResetPending, error: activeCounts.error, retry: activeCounts.refetch, loadMore: () => { if (!activeCounts.isFetching && activeNextCursor && activeNextCursor !== activeCursor) setActiveCursor(activeNextCursor); }, canManage, areaId, areas, setAreaId, onSelect: selectCount, onStart: () => create.mutate(), starting: create.isPending, message, onCancelled: resetActiveList });
  if (count.isPending) return <TableSkeleton rows={5} cols={4} />;
  if (count.isError) return <InlineState title={isForbidden(count.error) ? 'Count access forbidden' : 'Could not load count'} error={count.error} retry={count.refetch} />;
  const current = count.data!; const status = current.count.status; const editable = status === 'frozen' && canManage; const allRecorded = current.lines.every(line => line.countedQuantityMicros !== undefined); const canCancel = canManage && (status === 'draft' || status === 'frozen' || status === 'reviewed'); const knownStatus = status === 'draft' || status === 'frozen' || status === 'reviewed' || status === 'posted' || status === 'cancelled';
  return <section className="space-y-5"><div className="rounded-2xl border border-dark-800 bg-dark-900/70 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-medium uppercase tracking-wider ${status === 'cancelled' ? 'bg-dark-700 text-dark-300' : status === 'posted' ? 'bg-accent-emerald/10 text-accent-emerald' : 'bg-primary-500/10 text-primary-300'}`}>{knownStatus ? status : 'legacy status'}</span><span className="text-xs text-dark-500">Version {current.count.version}</span></div><h2 className="mt-3 text-xl font-semibold text-white">Physical count</h2><p className="mt-1 text-sm text-dark-400">Snapshot {current.count.cutoffAt ? new Date(current.count.cutoffAt).toLocaleString() : 'not frozen yet'}. Record what is physically present, not what should be there.</p></div><div className="flex flex-wrap gap-2">{status === 'draft' && canManage && <Button disabled={freeze.isPending} onClick={() => freeze.mutate()}>{freeze.isPending ? 'Freezing…' : 'Freeze snapshot'}</Button>}{status === 'frozen' && canManage && <Button disabled={!allRecorded || review.isPending} onClick={() => review.mutate()}>{review.isPending ? 'Reviewing…' : 'Review count'}</Button>}{status === 'reviewed' && canPost && <Button disabled={post.isPending} onClick={() => post.mutate()}>{post.isPending ? 'Posting…' : 'Post count'}</Button>}{canCancel && <Button variant="secondary" disabled={cancel.isPending} onClick={() => cancel.mutate()}>{cancel.isPending ? 'Cancelling…' : 'Cancel count'}</Button>}</div></div>{(status === 'frozen' || status === 'reviewed') && <Alert variant="info" className="mt-4">This count holds the storage area snapshot. Normal inventory activity is blocked there until the count is posted or cancelled.</Alert>}{status === 'cancelled' && <Alert variant="info" className="mt-4">This count was cancelled. No count adjustments were posted, and normal inventory activity is available again.</Alert>}{!knownStatus && <Alert variant="info" className="mt-4">This count uses a status from an older workflow. No lifecycle actions are available until it is refreshed or resolved by an administrator.</Alert>}{!canManage && status !== 'posted' && status !== 'cancelled' && <Alert variant="info" className="mt-4">Read-only review. Inventory manage permission is required to freeze, discover, record, review, or cancel this count.</Alert>}{message && <Alert variant={message.toLowerCase().includes('error') ? 'error' : 'info'} className="mt-4">{message}</Alert>}</div>
    {editable && <section className="rounded-2xl border border-primary-500/15 bg-primary-500/5 p-5"><h3 className="font-semibold text-white">Discovered stock</h3><p className="mt-1 text-sm text-dark-400">Found an item that was not in the frozen snapshot? Add it as a zero-book line, then record the physical quantity below.</p><div className="mt-4 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><Select label="Item" value={discoverItemId} onChange={e => { setDiscoverItemId(e.target.value); setDiscoverLotId(''); }}><option value="">Choose an item</option>{items.map(item => <option key={item.id} value={item.id}>{item.name}{item.sku ? ` (${item.sku})` : ''}</option>)}</Select><Select label={`Lot (${items.find(item => item.id === discoverItemId)?.lotTracking ?? 'optional'})`} value={discoverLotId} disabled={!discoverItemId || discoveredLots.isPending || items.find(item => item.id === discoverItemId)?.lotTracking === ''} onChange={e => setDiscoverLotId(e.target.value)}><option value="">No lot</option>{(discoveredLots.data?.lots ?? []).map(lot => <option key={lot.id} value={lot.id}>{lot.code} · {lot.status}{lot.expiresAt ? ` · expires ${new Date(lot.expiresAt).toLocaleDateString()}` : ''}</option>)}</Select><Button disabled={!discoverItemId || discover.isPending || (items.find(item => item.id === discoverItemId)?.lotTracking === 'required' && !discoverLotId)} onClick={() => discover.mutate()}>{discover.isPending ? 'Adding…' : 'Add discovered line'}</Button></div>{discoveredLots.isError && <p className="mt-2 text-xs text-red-400">Could not load lots for this item. Choose no lot or retry before adding.</p>}</section>}
    <div className="overflow-hidden rounded-2xl border border-dark-800 bg-dark-900/50"><div className="border-b border-dark-800 px-5 py-4"><h3 className="font-semibold text-white">Count lines</h3><p className="text-xs text-dark-500">Expected is the frozen snapshot. Difference is counted minus expected.</p></div>{current.lines.length === 0 ? <State icon={Package} title="No lines in this snapshot" copy="This storage area had no stock lines to count. A manager can add discovered zero-book items after freezing." compact /> : <div className="divide-y divide-dark-800">{current.lines.map(line => <CountLine key={line.id} line={line} item={items.find(item => item.id === line.itemId)} value={lineInputs[line.id] ?? microsToDecimal(line.countedQuantityMicros)} editable={editable && !record.isPending} onChange={value => setLineInputs(inputs => ({ ...inputs, [line.id]: value }))} onSave={() => record.mutate({ line, value: lineInputs[line.id] ?? microsToDecimal(line.countedQuantityMicros) })} />)}</div>}</div></section>;
}

function CountLine({ line, item, value, editable, onChange, onSave }: { line: StockCountLine; item?: InventoryItemReference; value: string; editable: boolean; onChange: (value: string) => void; onSave: () => void }) { const difference = line.countedQuantityMicros === undefined ? undefined : String(Number(line.countedQuantityMicros) - Number(line.snapshotQuantityMicros)); return <div className="grid gap-4 px-5 py-4 md:grid-cols-[1fr_auto_auto_auto] md:items-center"><div><p className="font-medium text-white">{item?.name ?? 'Unknown item'}{item?.sku && <span className="ml-2 text-xs text-dark-500">{item.sku}</span>}</p><p className="mt-1 text-xs text-dark-500">Expected {qty(line.snapshotQuantityMicros)} · {line.lotCode ?? (line.lotId ? 'Lot details unavailable' : 'No lot')}{line.lotStatus ? ` · ${line.lotStatus}` : ''}{line.lotExpiresAt ? ` · expires ${new Date(line.lotExpiresAt).toLocaleDateString()}` : ''}</p></div><div><label className="text-xs text-dark-500">Counted</label><Input aria-label={`Counted quantity for ${item?.name ?? 'item'}`} inputMode="decimal" value={value} disabled={!editable} onChange={event => onChange(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && editable) onSave(); }} /></div><div className="min-w-24"><p className="text-xs text-dark-500">Difference</p><p className={`font-semibold ${difference === undefined ? 'text-dark-600' : Number(difference) === 0 ? 'text-accent-emerald' : 'text-amber-300'}`}>{difference === undefined ? 'Not counted' : signedQty(difference)}</p></div>{editable && <Button variant="secondary" size="sm" onClick={onSave}>Save</Button>}</div>; }

function ReconciliationPanel({ locationId, principal, tenant, areas, items, canRead, canManage }: { locationId: string; principal: string; tenant: string; areas: InventoryStorageAreaReference[]; items: InventoryItemReference[]; canRead: boolean; canManage: boolean }) { void principal; void tenant; const [areaId, setAreaId] = useState(''); const [run, setRun] = useState<ReconciliationRun>(); const [message, setMessage] = useState(''); const detect = useMutation({ mutationFn: (repair: boolean) => inventoryApi.reconcile(locationId, areaId || undefined, newKey(), repair), onSuccess: result => { setRun(result.run); setMessage(result.run.status === 'repaired' ? 'Repair completed and recorded as a reconciliation run.' : 'Reconciliation completed. No stock was changed.'); }, onError: error => setMessage(getErrorMessage(error)) }); if (!canRead) return <State icon={LockKeyhole} title="Reconciliation access unavailable" copy="You need inventory read access to inspect reconciliation results at this location." />; return <section className="space-y-5"><div className="rounded-2xl border border-dark-800 bg-dark-900/70 p-5 sm:p-6"><div className="flex items-start gap-3"><ScanSearch className="mt-1 h-5 w-5 text-primary-400" /><div><h2 className="text-lg font-semibold text-white">Reconciliation</h2><p className="mt-1 max-w-2xl text-sm text-dark-400">Detect differences between the journal and stored balances. Detection is read-only. Repair is a separate, authorized action that restores balances to the journal; it is not a physical count.</p></div></div><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end"><Select label="Storage area (optional)" value={areaId} onChange={e => setAreaId(e.target.value)} className="min-w-0 flex-1"><option value="">All active areas</option>{areas.map(area => <option key={area.id} value={area.id}>{area.name}</option>)}</Select><Button disabled={detect.isPending} onClick={() => detect.mutate(false)}>{detect.isPending ? 'Checking…' : 'Detect differences'}</Button></div>{message && <Alert variant="info" className="mt-4">{message}</Alert>}</div>{run ? <ReconciliationResult run={run} items={items} canManage={canManage} onRepair={() => { if (window.confirm('This will change stored inventory balances to match the journal. It will not record a physical count. Continue?')) detect.mutate(true); }} /> : <State icon={ScanSearch} title="No reconciliation run yet" copy="Run a detection to see whether stored balances match the inventory journal." compact />}</section>; }

function ReconciliationResult({ run, items, canManage, onRepair }: { run: ReconciliationRun; items: InventoryItemReference[]; canManage: boolean; onRepair: () => void }) { return <section className="overflow-hidden rounded-2xl border border-dark-800 bg-dark-900/50"><div className="flex flex-col gap-4 border-b border-dark-800 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs uppercase tracking-wider ${run.status === 'repaired' ? 'bg-accent-emerald/10 text-accent-emerald' : 'bg-amber-400/10 text-amber-300'}`}>{run.status}</span><span className="text-xs text-dark-500">{new Date(run.completedAt).toLocaleString()}</span></div><h3 className="mt-2 font-semibold text-white">{run.mismatchCount === 0 ? 'Balances match the journal' : `${run.mismatchCount} difference${run.mismatchCount === 1 ? '' : 's'} detected`}</h3></div>{run.status === 'detected' && run.mismatchCount > 0 && canManage && <Button variant="secondary" onClick={onRepair}>Authorize balance repair</Button>}</div>{run.status === 'detected' && run.mismatchCount > 0 && <Alert variant="info" className="m-5">Repair changes stored balance records only. Review the differences and authorize it separately; it does not replace a physical count or post a stock movement.</Alert>}{run.mismatches.length > 0 && <div className="divide-y divide-dark-800">{run.mismatches.map((mismatch, index) => <div key={`${mismatch.itemId}-${index}`} className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_auto_auto_auto]"><span className="font-medium text-white">{items.find(item => item.id === mismatch.itemId)?.name ?? 'Unknown item'}</span><span className="text-sm text-dark-400">Journal {qty(mismatch.expectedQuantityMicros)}</span><span className="text-sm text-dark-400">Stored {qty(mismatch.actualQuantityMicros)}</span><span className="text-sm font-semibold text-amber-300">Delta {signedQty(mismatch.deltaMicros)}</span></div>)}</div>}{run.truncated && <p className="px-5 py-4 text-xs text-dark-500">Only the first 1,000 differences are shown.</p>}</section>; }
function State({ icon: Icon, title, copy, compact = false, action }: { icon: typeof Package; title: string; copy: string; compact?: boolean; action?: () => void }) { return <section className={`flex flex-col items-center rounded-2xl border border-dark-800 bg-dark-900/50 px-6 text-center ${compact ? 'py-12' : 'py-20'}`}><Icon className="mb-4 h-9 w-9 text-primary-400" /><h2 className="font-semibold text-white">{title}</h2><p className="mt-2 max-w-md text-sm text-dark-400">{copy}</p>{action && <Button variant="secondary" className="mt-4 inline-flex items-center gap-2" onClick={action}><RefreshCw className="h-4 w-4" />Retry</Button>}</section>; }
function InlineState({ title, error, retry }: { title: string; error: unknown; retry: () => void }) { return <div className="flex flex-col items-center px-6 py-14 text-center"><AlertCircle className="mb-3 h-8 w-8 text-red-400" /><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm text-dark-400">{getErrorMessage(error)}</p><Button variant="secondary" className="mt-4 inline-flex items-center gap-2" onClick={retry}><RefreshCw className="h-4 w-4" />Retry</Button></div>; }
function Tab({ active, onClick, icon: Icon, children }: { active: boolean; onClick: () => void; icon: typeof Package; children: string }) { return <button onClick={onClick} className={`flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${active ? 'bg-dark-700 text-white' : 'text-dark-400 hover:bg-dark-800 hover:text-white'}`}><Icon className="h-4 w-4" />{children}</button>; }
function BalanceTable({ rows, names, areaNames }: { rows: StockBalance[]; names: Record<string, string>; areaNames: Record<string, string> }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-dark-950/40 text-xs uppercase tracking-wider text-dark-500"><tr><th className="px-5 py-3">Item</th><th className="px-5 py-3">Area</th><th className="px-5 py-3 text-right">On hand</th><th className="px-5 py-3">Updated</th></tr></thead><tbody className="divide-y divide-dark-800">{rows.map(r => <tr key={r.id}><td className="px-5 py-4 font-medium text-white">{names[r.itemId] ?? 'Unknown item'}{r.lotId && <span className="ml-2 rounded bg-primary-500/10 px-2 py-0.5 text-[11px] text-primary-300">lot tracked</span>}</td><td className="px-5 py-4 text-dark-300">{areaNames[r.storageAreaId] ?? 'Unknown area'}</td><td className="px-5 py-4 text-right font-semibold text-accent-emerald">{qty(r.quantityMicros)}</td><td className="px-5 py-4 text-dark-500">{new Date(r.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>; }
function JournalTable({ entries, names, areaNames }: { entries: JournalEntry[]; names: Record<string, string>; areaNames: Record<string, string> }) { return <div className="divide-y divide-dark-800">{entries.map(e => <article key={e.posting.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-white">{prettyType[e.posting.type] ?? e.posting.type}</span><span className="text-xs text-dark-500">{new Date(e.posting.effectiveAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-dark-400">{names[e.movement.itemId] ?? 'Inventory entry'} · {areaNames[e.movement.storageAreaId] ?? 'Storage area'}{e.posting.reason ? ` · ${e.posting.reason}` : ''}</p></div><span className={`text-sm ${Number(e.movement.quantityMicros) < 0 ? 'text-red-300' : 'text-accent-emerald'}`}>{qty(e.movement.quantityMicros)}</span><span className="font-mono text-[11px] text-dark-600">{e.posting.id.slice(-8)}</span></article>)}</div>; }

type EntryPanelProps = { canPost: boolean; canManage: boolean; items: InventoryItemReference[]; areas: InventoryStorageAreaReference[]; locations: Array<{ id: string; name: string; isActive: boolean }>; destinationAreas: InventoryStorageAreaReference[]; entryType: 'opening_balance' | 'adjustment' | 'waste' | 'transfer'; setEntryType: (value: 'opening_balance' | 'adjustment' | 'waste' | 'transfer') => void; form: { itemId: string; storageAreaId: string; quantity: string; reason: string; idempotencyKey: string; lotId: string; destinationLocationId: string; destinationStorageAreaId: string }; errors: InventoryFormErrors; set: (key: keyof EntryPanelProps['form'], value: string) => void; submit: (event: FormEvent) => void; pending: boolean; message: string; lots: StockLot[]; lotsLoading: boolean; lotsError: unknown; selectableLots: StockLot[]; lotRequired: boolean; needsAvailability: boolean; createLot: (code: string, expiresAt?: string) => void; creatingLot: boolean };

function EntryPanel(props: EntryPanelProps) {
  const { canPost, canManage, items, areas, locations, destinationAreas, entryType, setEntryType, form, errors, set, submit, pending, message, lots, lotsLoading, lotsError, selectableLots, lotRequired, needsAvailability, createLot, creatingLot } = props;
  const [showCreateLot, setShowCreateLot] = useState(false);
  const [lotCode, setLotCode] = useState('');
  const [lotExpiry, setLotExpiry] = useState('');
  const canCreateLot = canManage && (entryType === 'adjustment' || entryType === 'opening_balance') && Number(form.quantity) > 0 && !!form.itemId;
  const lotHelp = lotRequired ? 'Required for this item.' : 'Optional for this item.';
  const submitLot = () => { if (!lotCode.trim() || !canCreateLot) return; createLot(lotCode.trim(), lotExpiry || undefined); setLotCode(''); setLotExpiry(''); setShowCreateLot(false); };
  return <section className="rounded-2xl border border-dark-800 bg-dark-900/70 p-5 sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="mb-1 flex items-center gap-2 text-primary-400"><ArrowRightLeft className="h-4 w-4" /><span className="text-xs font-medium uppercase tracking-wider">Post a movement</span></div><h2 className="text-lg font-semibold text-white">Record inventory</h2><p className="mt-1 text-sm text-dark-500">Every entry is permanent. Corrections are made by reversal.</p></div><ShieldAlert className="h-5 w-5 text-dark-600" /></div>
    {!canPost ? <div className="rounded-xl border border-dark-800 bg-dark-950/50 p-4 text-sm text-dark-400">You have read-only access to inventory. A user with <span className="text-dark-200">inventory post</span> permission must record movements.</div> : <form onSubmit={submit} noValidate className="space-y-4"><div className="grid gap-2 sm:grid-cols-3">{(['adjustment', 'waste', 'transfer'] as const).map(type => <button type="button" key={type} onClick={() => setEntryType(type)} className={`rounded-lg border px-3 py-2 text-sm font-medium capitalize transition ${entryType === type ? 'border-primary-500/60 bg-primary-500/10 text-primary-300' : 'border-dark-700 text-dark-400 hover:border-dark-600'}`}>{type === 'adjustment' ? 'Adjust stock' : type}</button>)}</div><div className="grid gap-4 md:grid-cols-2"><Select label="Item" value={form.itemId} error={errors.itemId} onChange={e => set('itemId', e.target.value)}><option value="">Choose an item</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</Select><Select label={entryType === 'transfer' ? 'Source area' : 'Storage area'} value={form.storageAreaId} error={errors.storageAreaId} onChange={e => set('storageAreaId', e.target.value)}><option value="">Choose an area</option>{areas.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</Select><Input label="Quantity" inputMode="decimal" placeholder="0.000000" value={form.quantity} error={errors.quantity} onChange={e => set('quantity', e.target.value)} /><Input label="Reason" placeholder={entryType === 'waste' ? 'Spillage during prep' : 'Count correction'} value={form.reason} error={errors.reason} onChange={e => set('reason', e.target.value)} /></div>
      {form.itemId && <div className="rounded-xl border border-dark-800 bg-dark-950/30 p-4"><div className="grid gap-4 md:grid-cols-[1fr_auto] md:items-end"><Select id="inventory-lot" label={`Lot (${lotHelp})`} value={form.lotId} error={errors.lotId} disabled={lotsLoading || selectableLots.length === 0} onChange={e => set('lotId', e.target.value)}><option value="">{lotsLoading ? 'Loading lots…' : needsAvailability ? 'Choose an in-stock lot' : 'No lot selected'}</option>{selectableLots.map(lot => <option key={lot.id} value={lot.id}>{lot.code}{lot.expiresAt ? ` · expires ${new Date(lot.expiresAt).toLocaleDateString()}` : ''}</option>)}</Select>{canCreateLot && <Button type="button" variant="secondary" size="sm" onClick={() => setShowCreateLot(value => !value)}>{showCreateLot ? 'Cancel' : 'Create lot'}</Button>}</div>{lotsError !== undefined && lotsError !== null && <p className="mt-2 text-xs text-red-400">Lots could not be loaded. Refresh before posting.</p>}{needsAvailability && <p className="mt-2 text-xs text-dark-500">Only available, unexpired lots with stock in the selected source area are shown.</p>}{!lotsLoading && (lotsError === undefined || lotsError === null) && lots.length === 0 && <p className="mt-2 text-xs text-dark-500">No lots exist for this item yet.</p>}
        {showCreateLot && canCreateLot && <div className="mt-4 grid gap-3 border-t border-dark-800 pt-4 sm:grid-cols-[1fr_auto_auto] sm:items-end"><Input label="New lot code" value={lotCode} placeholder="LOT-2026-001" onChange={e => setLotCode(e.target.value)} /><Input label="Expiry (optional)" type="date" value={lotExpiry} onChange={e => setLotExpiry(e.target.value)} /><Button type="button" disabled={!lotCode.trim() || creatingLot} onClick={submitLot}>{creatingLot ? 'Creating…' : 'Create and select'}</Button></div>}</div>}
      {entryType === 'transfer' && <div className="grid gap-4 rounded-xl border border-primary-500/15 bg-primary-500/5 p-4 md:grid-cols-2"><Select label="Destination location" value={form.destinationLocationId} error={errors.destinationLocationId} onChange={e => { set('destinationLocationId', e.target.value); set('destinationStorageAreaId', ''); }}><option value="">Choose a location</option>{locations.filter(l => l.isActive).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</Select><Select label="Destination area" value={form.destinationStorageAreaId} error={errors.destinationStorageAreaId} onChange={e => set('destinationStorageAreaId', e.target.value)}><option value="">Choose an area</option>{destinationAreas.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</Select><p className="text-xs text-dark-500 md:col-span-2">The source is <strong className="text-dark-300">{areas.find(a => a.id === form.storageAreaId)?.name ?? 'not selected'}</strong>; the destination is recorded separately for a complete audit trail.</p></div>}<Input label="Idempotency key" value={form.idempotencyKey} error={errors.idempotencyKey} onChange={e => set('idempotencyKey', e.target.value)} /><div className="flex items-center justify-between gap-3">{message ? <p className={`flex items-center gap-2 text-sm ${message.includes('posted') || message.includes('selected') ? 'text-accent-emerald' : 'text-red-400'}`}><CheckCircle2 className="h-4 w-4" />{message}</p> : <span className="text-xs text-dark-600">Safe to retry with the same key.</span>}<Button type="submit" disabled={pending} className="inline-flex items-center gap-2">{pending && <RefreshCw className="h-4 w-4 animate-spin" />}{pending ? 'Posting...' : 'Post entry'}</Button></div></form>}
  </section>;
}

function LotTable({ itemId, lots, canManage }: { itemId: string; lots: StockLot[]; canManage: boolean }) { const queryClient = useQueryClient(); const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: StockLot['status'] }) => inventoryApi.updateLot(itemId, id, status), onSuccess: () => queryClient.invalidateQueries({ queryKey: inventoryKeys.all }) }); return lots.length === 0 ? <State icon={Clock3} title="No lots recorded" copy="This item has no lot records yet." compact /> : <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-dark-500"><tr><th className="px-3 py-3">Lot</th><th className="px-3 py-3">Received</th><th className="px-3 py-3">Expiry</th><th className="px-3 py-3">Status</th><th /></tr></thead><tbody className="divide-y divide-dark-800">{lots.map(lot => { const expired = lot.expiresAt && new Date(lot.expiresAt) < new Date(); return <tr key={lot.id}><td className="px-3 py-4 font-medium text-white">{lot.code}</td><td className="px-3 py-4 text-dark-400">{new Date(lot.receivedAt).toLocaleDateString()}</td><td className={`px-3 py-4 ${expired ? 'font-medium text-red-400' : 'text-dark-400'}`}>{lot.expiresAt ? new Date(lot.expiresAt).toLocaleDateString() : 'No expiry'}{expired && ' · expired'}</td><td className="px-3 py-4"><span className={`rounded-full px-2 py-1 text-xs ${lot.status === 'quarantined' ? 'bg-amber-400/10 text-amber-300' : 'bg-accent-emerald/10 text-accent-emerald'}`}>{lot.status === 'quarantined' ? 'Quarantined' : 'Available'}</span></td><td className="px-3 py-4 text-right">{canManage && <Button size="sm" variant="secondary" disabled={update.isPending} onClick={() => update.mutate({ id: lot.id, status: lot.status === 'available' ? 'quarantined' : 'available' })}>{lot.status === 'available' ? 'Quarantine' : 'Release'}</Button>}</td></tr>; })}</tbody></table></div>; }
